TOP_50_COUNTRIES = [
    {"name": "France",               "flag": "🇫🇷", "rank": 1,  "cities": ["Paris", "Marseille"]},
    {"name": "Spain",                "flag": "🇪🇸", "rank": 2,  "cities": ["Barcelona", "Madrid"]},
    {"name": "United States",        "flag": "🇺🇸", "rank": 3,  "cities": ["New York", "Los Angeles"]},
    {"name": "China",                "flag": "🇨🇳", "rank": 4,  "cities": ["Shanghai", "Beijing"]},
    {"name": "Italy",                "flag": "🇮🇹", "rank": 5,  "cities": ["Rome", "Venice"]},
    {"name": "Turkey",               "flag": "🇹🇷", "rank": 6,  "cities": ["Istanbul", "Antalya"]},
    {"name": "Mexico",               "flag": "🇲🇽", "rank": 7,  "cities": ["Mexico City", "Cancún"]},
    {"name": "Thailand",             "flag": "🇹🇭", "rank": 8,  "cities": ["Bangkok", "Phuket"]},
    {"name": "Germany",              "flag": "🇩🇪", "rank": 9,  "cities": ["Berlin", "Munich"]},
    {"name": "United Kingdom",       "flag": "🇬🇧", "rank": 10, "cities": ["London", "Edinburgh"]},
    {"name": "Japan",                "flag": "🇯🇵", "rank": 11, "cities": ["Tokyo", "Osaka"]},
    {"name": "Austria",              "flag": "🇦🇹", "rank": 12, "cities": ["Vienna", "Salzburg"]},
    {"name": "Greece",               "flag": "🇬🇷", "rank": 13, "cities": ["Athens", "Santorini"]},
    {"name": "Malaysia",             "flag": "🇲🇾", "rank": 14, "cities": ["Kuala Lumpur", "Penang"]},
    {"name": "Portugal",             "flag": "🇵🇹", "rank": 15, "cities": ["Lisbon", "Porto"]},
    {"name": "Russia",               "flag": "🇷🇺", "rank": 16, "cities": ["Moscow", "St. Petersburg"]},
    {"name": "United Arab Emirates", "flag": "🇦🇪", "rank": 17, "cities": ["Dubai", "Abu Dhabi"]},
    {"name": "Canada",               "flag": "🇨🇦", "rank": 18, "cities": ["Toronto", "Vancouver"]},
    {"name": "Poland",               "flag": "🇵🇱", "rank": 19, "cities": ["Warsaw", "Kraków"]},
    {"name": "Netherlands",          "flag": "🇳🇱", "rank": 20, "cities": ["Amsterdam", "Rotterdam"]},
    {"name": "Vietnam",              "flag": "🇻🇳", "rank": 21, "cities": ["Ho Chi Minh City", "Hanoi"]},
    {"name": "India",                "flag": "🇮🇳", "rank": 22, "cities": ["Mumbai", "Delhi"]},
    {"name": "Croatia",              "flag": "🇭🇷", "rank": 23, "cities": ["Dubrovnik", "Split"]},
    {"name": "South Korea",          "flag": "🇰🇷", "rank": 24, "cities": ["Seoul", "Busan"]},
    {"name": "Singapore",            "flag": "🇸🇬", "rank": 25, "cities": ["Marina Bay", "Sentosa"]},
    {"name": "Egypt",                "flag": "🇪🇬", "rank": 26, "cities": ["Cairo", "Luxor"]},
    {"name": "Indonesia",            "flag": "🇮🇩", "rank": 27, "cities": ["Bali", "Jakarta"]},
    {"name": "Brazil",               "flag": "🇧🇷", "rank": 28, "cities": ["Rio de Janeiro", "São Paulo"]},
    {"name": "Australia",            "flag": "🇦🇺", "rank": 29, "cities": ["Sydney", "Melbourne"]},
    {"name": "Switzerland",          "flag": "🇨🇭", "rank": 30, "cities": ["Zurich", "Geneva"]},
    {"name": "Morocco",              "flag": "🇲🇦", "rank": 31, "cities": ["Marrakech", "Casablanca"]},
    {"name": "Saudi Arabia",         "flag": "🇸🇦", "rank": 32, "cities": ["Riyadh", "Jeddah"]},
    {"name": "South Africa",         "flag": "🇿🇦", "rank": 33, "cities": ["Cape Town", "Johannesburg"]},
    {"name": "Philippines",          "flag": "🇵🇭", "rank": 34, "cities": ["Manila", "Cebu"]},
    {"name": "Sweden",               "flag": "🇸🇪", "rank": 35, "cities": ["Stockholm", "Gothenburg"]},
    {"name": "Argentina",            "flag": "🇦🇷", "rank": 36, "cities": ["Buenos Aires", "Córdoba"]},
    {"name": "Norway",               "flag": "🇳🇴", "rank": 37, "cities": ["Oslo", "Bergen"]},
    {"name": "New Zealand",          "flag": "🇳🇿", "rank": 38, "cities": ["Auckland", "Queenstown"]},
    {"name": "Chile",                "flag": "🇨🇱", "rank": 39, "cities": ["Santiago", "Valparaíso"]},
    {"name": "Ireland",              "flag": "🇮🇪", "rank": 40, "cities": ["Dublin", "Galway"]},
    {"name": "Belgium",              "flag": "🇧🇪", "rank": 41, "cities": ["Brussels", "Bruges"]},
    {"name": "Peru",                 "flag": "🇵🇪", "rank": 42, "cities": ["Lima", "Cusco"]},
    {"name": "Colombia",             "flag": "🇨🇴", "rank": 43, "cities": ["Bogotá", "Medellín"]},
    {"name": "Finland",              "flag": "🇫🇮", "rank": 44, "cities": ["Helsinki", "Rovaniemi"]},
    {"name": "Denmark",              "flag": "🇩🇰", "rank": 45, "cities": ["Copenhagen", "Aarhus"]},
    {"name": "Iceland",              "flag": "🇮🇸", "rank": 46, "cities": ["Reykjavik", "Akureyri"]},
    {"name": "Kenya",                "flag": "🇰🇪", "rank": 47, "cities": ["Nairobi", "Mombasa"]},
    {"name": "Nepal",                "flag": "🇳🇵", "rank": 48, "cities": ["Kathmandu", "Pokhara"]},
    {"name": "Sri Lanka",            "flag": "🇱🇰", "rank": 49, "cities": ["Colombo", "Kandy"]},
    {"name": "Maldives",             "flag": "🇲🇻", "rank": 50, "cities": ["Malé", "Maafushi"]},
]

# Tier pools for board generation
TIER_BUDGET   = [c for c in TOP_50_COUNTRIES if c["rank"] >= 36]  # rank 36-50
TIER_MID_LOW  = [c for c in TOP_50_COUNTRIES if 24 <= c["rank"] <= 35]  # rank 24-35
TIER_MID_HIGH = [c for c in TOP_50_COUNTRIES if 16 <= c["rank"] <= 23]  # rank 16-23
TIER_PREMIUM  = [c for c in TOP_50_COUNTRIES if c["rank"] <= 15]  # rank 1-15
